### ISSUE TITLE
Double chat text

### ISSUE THREAD

**Issue by drag1c** [ShadowsAdi/CSGORemake#11] opened 2021-12-21 16:25 UTC
Almost all the time say message is duplicated. For example:
Say: blabla

[Rank XXX] User: blabla
User: blabla

Dunno what is a reason.

Why I cant see .sma file for main plugin?

**Comment by ShadowsAdi** [comment] 2021-12-22 09:45
Hello, thank you for your issue report, I am gonna look into it.
Also, source code ( .sma ) is not open source yet, it will be soon.

**Comment by ShadowsAdi** [comment] 2021-12-23 08:09
I checked it out and it works fine, I think the problem is from other plugin which is using the chat, if you want, you can post the amxx plugins output here or check it by yourself.

**Comment by drag1c** [comment] 2021-12-23 21:20
Might be it's because of VIP plugin. I will test it.

**Comment by drag1c** [comment] 2021-12-23 21:26
kgb_admin_color_chat.amxx 			; Zeleni admin chat
amx_ejl_adminchat.amxx 			; Poboljsane amx_say, csay i tsay komande
adminfreelook.amxx
Map_Spawns_Editor.amxx 			; Popravlja spawnove na mapama gde nema dovoljno
task_scheduler.amxx 				; Izvrsavanje odlozenih komandi
rs.amxx 
ad_manager.amxx					; Reklame u configs/advertisements
; Pracenje rada servera
fps.amxx
temp_flags.amxx

accuracy_fix.amxx
exec.amxx
xredirect.amxx

; Statistika admina
online_logger.amxx
real_game_time.amxx

; Anticheat VPN & SteamID & bansystem
bypass_guard.amxx
bg_provider_geoip.amxx
restrictnames.amxx
swear_replacement.amxx
admin_commands_log.amxx
cmdchecker.amxx
;unreal_demo_helper.amxx

mode.amxx
models_replacement.amxx
admin_esp.amxx
accuracy_fix.amxx
kgbbots.amxx
amxgag.amxx
reaimdetector.amxx
fragcounter.amxx
walkguard.amxx
no_team_flash.amxx
demo_recorder.amxx
gamename_wins.amxx
bullet_damage.amxx
healthplus.amxx
kill_assist.amxx
custom_smoke.amxx
csgo_physics.amxx
grenadetrail_like_csgo.amxx

Dunno what causing it... I even stopped vip plugins and it did not change.

**Comment by drag1c** [comment] 2021-12-23 21:41
There was colision with several plugins it seems.
I turned them all off 👯‍♂️

**Comment by ShadowsAdi** [comment] 2021-12-24 08:43
Oki, marked as solved!

**Closed by ShadowsAdi** 2021-12-24 08:43 UTC
Labels: bug, good first issue
